version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
