services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
  backend:
    build: ./backend
    ports:
      - "5000:5000" # mapuj endpointy
      - "5001:5001" # na te porty
    environment:
      - ASPNETCORE_HTTP_PORT=https://+:5001
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      - "./backend:/app"