const zmienna = [{
  "id": 1,
  "first_name": "Amos",
  "surname": "Glassup",
  "email": "aglassup0@ustream.tv",
  "phone_number": "901-412-0756",
  "hire_date": "7/12/2002",
  "job_name": "Help Desk Operator",
  "salary": 52659.66,
  "commission": 4016.86,
  "manager": "Amos Glassup",
  "department_name": "Finance",
  "city": "La Jutosa",
  "country": "Honduras"
}, {
  "id": 2,
  "first_name": "Papagena",
  "surname": "Lucks",
  "email": "plucks1@bravesites.com",
  "phone_number": "644-136-4117",
  "hire_date": "9/21/2001",
  "job_name": "Geological Engineer",
  "salary": 42975.93,
  "commission": 855.14,
  "manager": "Papagena Lucks",
  "department_name": "Operations",
  "city": "Rizó",
  "country": "Greece"
}, {
  "id": 3,
  "first_name": "Mirna",
  "surname": "Wholesworth",
  "email": "mwholesworth2@t.co",
  "phone_number": "571-592-4275",
  "hire_date": "3/6/2015",
  "job_name": "Human Resources Manager",
  "salary": 113682.77,
  "commission": 2281.67,
  "manager": "Mirna Wholesworth",
  "department_name": "Marketing",
  "city": "Qal‘eh Ganj",
  "country": "Iran"
}, {
  "id": 4,
  "first_name": "Ammamaria",
  "surname": "Dudin",
  "email": "adudin3@umich.edu",
  "phone_number": "535-334-6288",
  "hire_date": "9/3/2015",
  "job_name": "Assistant Manager",
  "salary": 110417.36,
  "commission": 1558.53,
  "manager": "Ammamaria Dudin",
  "department_name": "IT",
  "city": "Flandes",
  "country": "Colombia"
}, {
  "id": 5,
  "first_name": "Nevsa",
  "surname": "Pool",
  "email": "npool4@stumbleupon.com",
  "phone_number": "134-226-9297",
  "hire_date": "9/21/2022",
  "job_name": "Professor",
  "salary": 108067.93,
  "commission": 1534.81,
  "manager": "Nevsa Pool",
  "department_name": "IT",
  "city": "Hobor",
  "country": "China"
}, {
  "id": 6,
  "first_name": "Rockie",
  "surname": "Crittal",
  "email": "rcrittal5@clickbank.net",
  "phone_number": "957-635-6498",
  "hire_date": "1/22/2016",
  "job_name": "Research Assistant I",
  "salary": 83278.26,
  "commission": 2251.51,
  "manager": "Rockie Crittal",
  "department_name": "Finance",
  "city": "Severnyy",
  "country": "Russia"
}, {
  "id": 7,
  "first_name": "Anne-marie",
  "surname": "Duignan",
  "email": "aduignan6@tmall.com",
  "phone_number": "752-395-0366",
  "hire_date": "11/3/2021",
  "job_name": "Senior Quality Engineer",
  "salary": 50697.91,
  "commission": 2668.88,
  "manager": "Anne-marie Duignan",
  "department_name": "Operations",
  "city": "Matur",
  "country": "Indonesia"
}, {
  "id": 8,
  "first_name": "Allison",
  "surname": "Stannion",
  "email": "astannion7@illinois.edu",
  "phone_number": "502-582-4047",
  "hire_date": "6/8/2011",
  "job_name": "Web Designer IV",
  "salary": 124974.85,
  "commission": 2020.27,
  "manager": "Allison Stannion",
  "department_name": "Marketing",
  "city": "Sundsvall",
  "country": "Sweden"
}, {
  "id": 9,
  "first_name": "Lou",
  "surname": "Freiburger",
  "email": "lfreiburger8@xing.com",
  "phone_number": "465-689-6487",
  "hire_date": "4/24/2016",
  "job_name": "Community Outreach Specialist",
  "salary": 110865.65,
  "commission": 4086.38,
  "manager": "Lou Freiburger",
  "department_name": "Finance",
  "city": "Banhā",
  "country": "Egypt"
}, {
  "id": 10,
  "first_name": "Dee dee",
  "surname": "Gerin",
  "email": "ddee9@nps.gov",
  "phone_number": "937-322-2783",
  "hire_date": "12/2/2000",
  "job_name": "Web Designer III",
  "salary": 118708.52,
  "commission": 1373.34,
  "manager": "Dee dee Gerin",
  "department_name": "Sales",
  "city": "Dafengdui",
  "country": "China"
}, {
  "id": 11,
  "first_name": "Leisha",
  "surname": "Reditt",
  "email": "lreditta@yandex.ru",
  "phone_number": "121-623-2456",
  "hire_date": "10/24/2015",
  "job_name": "Geologist IV",
  "salary": 128124.16,
  "commission": 3534.72,
  "manager": "Leisha Reditt",
  "department_name": "Finance",
  "city": "Qümong",
  "country": "China"
}, {
  "id": 12,
  "first_name": "Aldon",
  "surname": "Cramp",
  "email": "acrampb@theglobeandmail.com",
  "phone_number": "147-442-1735",
  "hire_date": "6/6/2006",
  "job_name": "Administrative Assistant IV",
  "salary": 111811.46,
  "commission": 3249.63,
  "manager": "Aldon Cramp",
  "department_name": "Finance",
  "city": "Pines",
  "country": "Philippines"
}, {
  "id": 13,
  "first_name": "Frasier",
  "surname": "Cottie",
  "email": "fcottiec@eventbrite.com",
  "phone_number": "741-137-5932",
  "hire_date": "4/27/2009",
  "job_name": "Software Engineer I",
  "salary": 28151.83,
  "commission": 2106.45,
  "manager": "Frasier Cottie",
  "department_name": "Finance",
  "city": "Xianglong",
  "country": "China"
}, {
  "id": 14,
  "first_name": "Daryle",
  "surname": "Pashen",
  "email": "dpashend@europa.eu",
  "phone_number": "401-340-8422",
  "hire_date": "5/8/2007",
  "job_name": "Structural Engineer",
  "salary": 37200.39,
  "commission": 4192.55,
  "manager": "Daryle Pashen",
  "department_name": "IT",
  "city": "Chenyang",
  "country": "China"
}, {
  "id": 15,
  "first_name": "Alice",
  "surname": "Wailes",
  "email": "awailese@comcast.net",
  "phone_number": "578-432-1515",
  "hire_date": "7/23/2018",
  "job_name": "Senior Developer",
  "salary": 49179.02,
  "commission": 2511.37,
  "manager": "Alice Wailes",
  "department_name": "Marketing",
  "city": "Santo Domingo",
  "country": "Philippines"
}, {
  "id": 16,
  "first_name": "Robina",
  "surname": "Stroulger",
  "email": "rstroulgerf@yellowpages.com",
  "phone_number": "673-623-2462",
  "hire_date": "10/13/2015",
  "job_name": "Paralegal",
  "salary": 133196.45,
  "commission": 2361.85,
  "manager": "Robina Stroulger",
  "department_name": "Operations",
  "city": "Bojawa",
  "country": "Indonesia"
}, {
  "id": 17,
  "first_name": "June",
  "surname": "Lovart",
  "email": "jlovartg@de.vu",
  "phone_number": "903-880-9329",
  "hire_date": "5/25/2018",
  "job_name": "Professor",
  "salary": 77610.15,
  "commission": 4343.45,
  "manager": "June Lovart",
  "department_name": "Finance",
  "city": "Wenwusha",
  "country": "China"
}, {
  "id": 18,
  "first_name": "Merle",
  "surname": "Becerro",
  "email": "mbecerroh@biblegateway.com",
  "phone_number": "400-573-8682",
  "hire_date": "7/9/2002",
  "job_name": "Cost Accountant",
  "salary": 148907.19,
  "commission": 1634.81,
  "manager": "Merle Becerro",
  "department_name": "Operations",
  "city": "Andou",
  "country": "China"
}, {
  "id": 19,
  "first_name": "Dominica",
  "surname": "Rustidge",
  "email": "drustidgei@163.com",
  "phone_number": "438-848-0850",
  "hire_date": "2/6/2004",
  "job_name": "Civil Engineer",
  "salary": 41581.48,
  "commission": 906.31,
  "manager": "Dominica Rustidge",
  "department_name": "Finance",
  "city": "Al Ḩammāmāt",
  "country": "Tunisia"
}, {
  "id": 20,
  "first_name": "Bunnie",
  "surname": "Finley",
  "email": "bfinleyj@ucoz.ru",
  "phone_number": "103-307-7595",
  "hire_date": "3/8/2005",
  "job_name": "Health Coach III",
  "salary": 63478.46,
  "commission": 3394.8,
  "manager": "Bunnie Finley",
  "department_name": "Operations",
  "city": "Gareba",
  "country": "Indonesia"
}, {
  "id": 21,
  "first_name": "Jermaine",
  "surname": "Trittam",
  "email": "jtrittamk@oaic.gov.au",
  "phone_number": "682-935-7733",
  "hire_date": "12/18/2010",
  "job_name": "Legal Assistant",
  "salary": 51093.21,
  "commission": 2439.26,
  "manager": "Jermaine Trittam",
  "department_name": "Sales",
  "city": "Fort Worth",
  "country": "United States"
}, {
  "id": 22,
  "first_name": "Wilie",
  "surname": "Peres",
  "email": "wperesl@imageshack.us",
  "phone_number": "562-434-4384",
  "hire_date": "8/28/2009",
  "job_name": "Editor",
  "salary": 97620.43,
  "commission": 66.7,
  "manager": "Wilie Peres",
  "department_name": "Marketing",
  "city": "Sidzina",
  "country": "Poland"
}, {
  "id": 23,
  "first_name": "Janine",
  "surname": "Crickmore",
  "email": "jcrickmorem@intel.com",
  "phone_number": "348-970-8847",
  "hire_date": "8/19/2002",
  "job_name": "Help Desk Operator",
  "salary": 28067.85,
  "commission": 4464.64,
  "manager": "Janine Crickmore",
  "department_name": "IT",
  "city": "Firá",
  "country": "Greece"
}, {
  "id": 24,
  "first_name": "Alvy",
  "surname": "Ayliff",
  "email": "aayliffn@hp.com",
  "phone_number": "540-744-5185",
  "hire_date": "1/6/2004",
  "job_name": "Technical Writer",
  "salary": 102746.18,
  "commission": 4139.66,
  "manager": "Alvy Ayliff",
  "department_name": "Finance",
  "city": "Essen",
  "country": "Germany"
}, {
  "id": 25,
  "first_name": "Bobinette",
  "surname": "Plane",
  "email": "bplaneo@nationalgeographic.com",
  "phone_number": "222-914-5512",
  "hire_date": "8/18/2004",
  "job_name": "Compensation Analyst",
  "salary": 114660.72,
  "commission": 3872.6,
  "manager": "Bobinette Plane",
  "department_name": "IT",
  "city": "Doyong",
  "country": "Philippines"
}, {
  "id": 26,
  "first_name": "George",
  "surname": "Riccardi",
  "email": "griccardip@oaic.gov.au",
  "phone_number": "957-638-9050",
  "hire_date": "1/18/2018",
  "job_name": "Librarian",
  "salary": 149809.2,
  "commission": 184.12,
  "manager": "George Riccardi",
  "department_name": "Marketing",
  "city": "Zgornje Pirniče",
  "country": "Slovenia"
}, {
  "id": 27,
  "first_name": "Nye",
  "surname": "Jovovic",
  "email": "njovovicq@creativecommons.org",
  "phone_number": "522-498-4042",
  "hire_date": "7/7/2018",
  "job_name": "Structural Engineer",
  "salary": 72104.95,
  "commission": 2560.93,
  "manager": "Nye Jovovic",
  "department_name": "Marketing",
  "city": "Brka",
  "country": "Bosnia and Herzegovina"
}, {
  "id": 28,
  "first_name": "Bonnee",
  "surname": "Caunt",
  "email": "bcauntr@columbia.edu",
  "phone_number": "263-244-7567",
  "hire_date": "11/6/2015",
  "job_name": "Computer Systems Analyst III",
  "salary": 81539.53,
  "commission": 1568.91,
  "manager": "Bonnee Caunt",
  "department_name": "Operations",
  "city": "Yukou",
  "country": "China"
}, {
  "id": 29,
  "first_name": "Cary",
  "surname": "Owthwaite",
  "email": "cowthwaites@sfgate.com",
  "phone_number": "288-495-9861",
  "hire_date": "5/25/2015",
  "job_name": "Office Assistant I",
  "salary": 78410.96,
  "commission": 2875.21,
  "manager": "Cary Owthwaite",
  "department_name": "Marketing",
  "city": "Hongyuan",
  "country": "China"
}, {
  "id": 30,
  "first_name": "Gerianne",
  "surname": "Happert",
  "email": "ghappertt@forbes.com",
  "phone_number": "445-343-2225",
  "hire_date": "12/12/2012",
  "job_name": "Web Designer III",
  "salary": 79126.52,
  "commission": 1632.07,
  "manager": "Gerianne Happert",
  "department_name": "Finance",
  "city": "Thetford-Mines",
  "country": "Canada"
}, {
  "id": 31,
  "first_name": "Dmitri",
  "surname": "Goscar",
  "email": "dgoscaru@uol.com.br",
  "phone_number": "879-936-3147",
  "hire_date": "2/7/2020",
  "job_name": "Web Designer IV",
  "salary": 81485.87,
  "commission": 395.48,
  "manager": "Dmitri Goscar",
  "department_name": "IT",
  "city": "Grijó",
  "country": "Portugal"
}, {
  "id": 32,
  "first_name": "Rebeca",
  "surname": "Lettuce",
  "email": "rlettucev@reference.com",
  "phone_number": "978-564-7386",
  "hire_date": "5/28/2010",
  "job_name": "Compensation Analyst",
  "salary": 95369.98,
  "commission": 1645.11,
  "manager": "Rebeca Lettuce",
  "department_name": "Finance",
  "city": "Makuyuni",
  "country": "Tanzania"
}, {
  "id": 33,
  "first_name": "Thorstein",
  "surname": "Wilder",
  "email": "twilderw@vkontakte.ru",
  "phone_number": "652-874-0208",
  "hire_date": "3/19/2016",
  "job_name": "Safety Technician I",
  "salary": 55834.16,
  "commission": 4531.48,
  "manager": "Thorstein Wilder",
  "department_name": "Marketing",
  "city": "Vegachí",
  "country": "Colombia"
}, {
  "id": 34,
  "first_name": "Britteny",
  "surname": "Girodon",
  "email": "bgirodonx@sohu.com",
  "phone_number": "654-717-3961",
  "hire_date": "8/22/2017",
  "job_name": "Financial Analyst",
  "salary": 147206.64,
  "commission": 580.51,
  "manager": "Britteny Girodon",
  "department_name": "Finance",
  "city": "Katori-shi",
  "country": "Japan"
}, {
  "id": 35,
  "first_name": "Boony",
  "surname": "De Cruze",
  "email": "bdey@chronoengine.com",
  "phone_number": "742-612-4356",
  "hire_date": "3/4/2011",
  "job_name": "Senior Quality Engineer",
  "salary": 147667.48,
  "commission": 2092.95,
  "manager": "Boony De Cruze",
  "department_name": "Operations",
  "city": "Zapolyarnyy",
  "country": "Russia"
}, {
  "id": 36,
  "first_name": "Torie",
  "surname": "Keitch",
  "email": "tkeitchz@storify.com",
  "phone_number": "170-906-6716",
  "hire_date": "12/29/2022",
  "job_name": "Human Resources Manager",
  "salary": 92254.71,
  "commission": 1900.49,
  "manager": "Torie Keitch",
  "department_name": "IT",
  "city": "Lautaro",
  "country": "Chile"
}, {
  "id": 37,
  "first_name": "Mersey",
  "surname": "Vanini",
  "email": "mvanini10@hibu.com",
  "phone_number": "812-543-3026",
  "hire_date": "12/30/2016",
  "job_name": "Research Assistant II",
  "salary": 121595.1,
  "commission": 1273.97,
  "manager": "Mersey Vanini",
  "department_name": "Finance",
  "city": "Skien",
  "country": "Norway"
}, {
  "id": 38,
  "first_name": "Fayth",
  "surname": "Strathearn",
  "email": "fstrathearn11@qq.com",
  "phone_number": "708-897-2213",
  "hire_date": "8/12/2016",
  "job_name": "Analog Circuit Design manager",
  "salary": 45749.54,
  "commission": 2921.4,
  "manager": "Fayth Strathearn",
  "department_name": "Sales",
  "city": "Nanshi",
  "country": "China"
}, {
  "id": 39,
  "first_name": "Yevette",
  "surname": "McGinnell",
  "email": "ymcginnell12@miitbeian.gov.cn",
  "phone_number": "225-467-7696",
  "hire_date": "11/9/2017",
  "job_name": "Programmer Analyst IV",
  "salary": 28957.55,
  "commission": 4177.39,
  "manager": "Yevette McGinnell",
  "department_name": "Operations",
  "city": "Enonkoski",
  "country": "Finland"
}, {
  "id": 40,
  "first_name": "Warde",
  "surname": "Kew",
  "email": "wkew13@amazon.co.uk",
  "phone_number": "422-498-9736",
  "hire_date": "5/8/2020",
  "job_name": "Mechanical Systems Engineer",
  "salary": 133506.22,
  "commission": 989.64,
  "manager": "Warde Kew",
  "department_name": "Marketing",
  "city": "Suchań",
  "country": "Poland"
}, {
  "id": 41,
  "first_name": "Frederica",
  "surname": "Fatkin",
  "email": "ffatkin14@studiopress.com",
  "phone_number": "346-685-3798",
  "hire_date": "3/18/2009",
  "job_name": "Operator",
  "salary": 42397.37,
  "commission": 3125.43,
  "manager": "Frederica Fatkin",
  "department_name": "IT",
  "city": "Consuelo",
  "country": "Philippines"
}, {
  "id": 42,
  "first_name": "Janina",
  "surname": "Cristoferi",
  "email": "jcristoferi15@jalbum.net",
  "phone_number": "138-678-1450",
  "hire_date": "3/26/2000",
  "job_name": "Web Developer III",
  "salary": 139778.95,
  "commission": 2381.19,
  "manager": "Janina Cristoferi",
  "department_name": "Operations",
  "city": "Ban Takhun",
  "country": "Thailand"
}, {
  "id": 43,
  "first_name": "Cristin",
  "surname": "Lyford",
  "email": "clyford16@gov.uk",
  "phone_number": "404-775-3064",
  "hire_date": "7/24/2008",
  "job_name": "Software Consultant",
  "salary": 40252.85,
  "commission": 4972.89,
  "manager": "Cristin Lyford",
  "department_name": "Finance",
  "city": "Mississauga",
  "country": "Canada"
}, {
  "id": 44,
  "first_name": "Trenton",
  "surname": "Shire",
  "email": "tshire17@angelfire.com",
  "phone_number": "343-142-3140",
  "hire_date": "2/25/2002",
  "job_name": "Accounting Assistant I",
  "salary": 119836.7,
  "commission": 4253.12,
  "manager": "Trenton Shire",
  "department_name": "Sales",
  "city": "Fatuulan",
  "country": "Indonesia"
}, {
  "id": 45,
  "first_name": "Sterling",
  "surname": "McKniely",
  "email": "smckniely18@about.com",
  "phone_number": "575-216-1019",
  "hire_date": "8/31/2003",
  "job_name": "Editor",
  "salary": 32604.69,
  "commission": 4387.51,
  "manager": "Sterling McKniely",
  "department_name": "Marketing",
  "city": "Cherbourg-Octeville",
  "country": "France"
}, {
  "id": 46,
  "first_name": "Gayel",
  "surname": "Gorry",
  "email": "ggorry19@globo.com",
  "phone_number": "459-801-8849",
  "hire_date": "4/30/2005",
  "job_name": "Environmental Specialist",
  "salary": 142451.36,
  "commission": 4895.31,
  "manager": "Gayel Gorry",
  "department_name": "Operations",
  "city": "Maagnas",
  "country": "Philippines"
}, {
  "id": 47,
  "first_name": "Florina",
  "surname": "Norquoy",
  "email": "fnorquoy1a@dailymotion.com",
  "phone_number": "132-815-3059",
  "hire_date": "3/3/2007",
  "job_name": "Chemical Engineer",
  "salary": 138206.77,
  "commission": 2017.01,
  "manager": "Florina Norquoy",
  "department_name": "Sales",
  "city": "Petaling Jaya",
  "country": "Malaysia"
}, {
  "id": 48,
  "first_name": "Beauregard",
  "surname": "Entwisle",
  "email": "bentwisle1b@ifeng.com",
  "phone_number": "465-144-1494",
  "hire_date": "2/25/2022",
  "job_name": "Developer III",
  "salary": 57341.65,
  "commission": 868.74,
  "manager": "Beauregard Entwisle",
  "department_name": "Sales",
  "city": "Stockholm",
  "country": "Sweden"
}, {
  "id": 49,
  "first_name": "Shantee",
  "surname": "Tours",
  "email": "stours1c@youku.com",
  "phone_number": "656-420-4046",
  "hire_date": "11/14/2006",
  "job_name": "Technical Writer",
  "salary": 123509.36,
  "commission": 1251.36,
  "manager": "Shantee Tours",
  "department_name": "Marketing",
  "city": "Wurigelebur",
  "country": "Indonesia"
}, {
  "id": 50,
  "first_name": "Brnaba",
  "surname": "Todari",
  "email": "btodari1d@exblog.jp",
  "phone_number": "448-412-2679",
  "hire_date": "8/3/2019",
  "job_name": "VP Marketing",
  "salary": 147476.85,
  "commission": 3125.68,
  "manager": "Brnaba Todari",
  "department_name": "IT",
  "city": "Novopavlovsk",
  "country": "Russia"
}, {
  "id": 51,
  "first_name": "Mendel",
  "surname": "Cheves",
  "email": "mcheves1e@utexas.edu",
  "phone_number": "698-541-6931",
  "hire_date": "12/23/2009",
  "job_name": "Registered Nurse",
  "salary": 110621.69,
  "commission": 1431.14,
  "manager": "Mendel Cheves",
  "department_name": "Finance",
  "city": "Lubaczów",
  "country": "Poland"
}, {
  "id": 52,
  "first_name": "Brady",
  "surname": "McMaster",
  "email": "bmcmaster1f@patch.com",
  "phone_number": "525-357-7972",
  "hire_date": "9/28/2008",
  "job_name": "VP Marketing",
  "salary": 65111.37,
  "commission": 4583.92,
  "manager": "Brady McMaster",
  "department_name": "Sales",
  "city": "Kruševac",
  "country": "Serbia"
}, {
  "id": 53,
  "first_name": "Hilary",
  "surname": "Schurig",
  "email": "hschurig1g@reuters.com",
  "phone_number": "503-321-7248",
  "hire_date": "1/24/2010",
  "job_name": "Quality Control Specialist",
  "salary": 141575.98,
  "commission": 2015.64,
  "manager": "Hilary Schurig",
  "department_name": "IT",
  "city": "Tuoshi",
  "country": "China"
}, {
  "id": 54,
  "first_name": "Erskine",
  "surname": "Greiser",
  "email": "egreiser1h@ft.com",
  "phone_number": "103-859-8320",
  "hire_date": "2/4/2016",
  "job_name": "VP Marketing",
  "salary": 137431.05,
  "commission": 3189.18,
  "manager": "Erskine Greiser",
  "department_name": "Sales",
  "city": "‘Awaj",
  "country": "Syria"
}, {
  "id": 55,
  "first_name": "Bartolemo",
  "surname": "Packington",
  "email": "bpackington1i@shop-pro.jp",
  "phone_number": "909-889-2756",
  "hire_date": "3/12/2012",
  "job_name": "Community Outreach Specialist",
  "salary": 141481.05,
  "commission": 2912.39,
  "manager": "Bartolemo Packington",
  "department_name": "Marketing",
  "city": "Videira",
  "country": "Brazil"
}, {
  "id": 56,
  "first_name": "Tiebold",
  "surname": "Edmundson",
  "email": "tedmundson1j@biglobe.ne.jp",
  "phone_number": "627-655-5379",
  "hire_date": "2/10/2008",
  "job_name": "VP Marketing",
  "salary": 94510.1,
  "commission": 3295.86,
  "manager": "Tiebold Edmundson",
  "department_name": "Sales",
  "city": "Daniëlskuil",
  "country": "South Africa"
}, {
  "id": 57,
  "first_name": "Tommy",
  "surname": "Minchin",
  "email": "tminchin1k@ebay.com",
  "phone_number": "574-978-1188",
  "hire_date": "9/30/2021",
  "job_name": "Engineer III",
  "salary": 85720.91,
  "commission": 2172.89,
  "manager": "Tommy Minchin",
  "department_name": "Operations",
  "city": "Wangpu",
  "country": "China"
}, {
  "id": 58,
  "first_name": "Georgeanne",
  "surname": "Dominetti",
  "email": "gdominetti1l@cbslocal.com",
  "phone_number": "454-761-6277",
  "hire_date": "6/29/2004",
  "job_name": "Graphic Designer",
  "salary": 96387.01,
  "commission": 2388.39,
  "manager": "Georgeanne Dominetti",
  "department_name": "IT",
  "city": "Tawangrejo",
  "country": "Indonesia"
}, {
  "id": 59,
  "first_name": "Brannon",
  "surname": "Tickle",
  "email": "btickle1m@irs.gov",
  "phone_number": "187-515-2533",
  "hire_date": "1/28/2014",
  "job_name": "Senior Developer",
  "salary": 71854.01,
  "commission": 4358.04,
  "manager": "Brannon Tickle",
  "department_name": "Marketing",
  "city": "Longhua",
  "country": "China"
}, {
  "id": 60,
  "first_name": "Sinclair",
  "surname": "Fentem",
  "email": "sfentem1n@sciencedirect.com",
  "phone_number": "902-586-5674",
  "hire_date": "4/18/2019",
  "job_name": "Design Engineer",
  "salary": 30326.71,
  "commission": 3140.92,
  "manager": "Sinclair Fentem",
  "department_name": "IT",
  "city": "Yongchang",
  "country": "China"
}, {
  "id": 61,
  "first_name": "Nevsa",
  "surname": "Skoggins",
  "email": "nskoggins1o@nydailynews.com",
  "phone_number": "506-192-9864",
  "hire_date": "7/25/2018",
  "job_name": "Nurse Practicioner",
  "salary": 89724.46,
  "commission": 161.3,
  "manager": "Nevsa Skoggins",
  "department_name": "Sales",
  "city": "Babice",
  "country": "Poland"
}, {
  "id": 62,
  "first_name": "Tore",
  "surname": "Teresia",
  "email": "tteresia1p@prnewswire.com",
  "phone_number": "220-947-7479",
  "hire_date": "7/13/2012",
  "job_name": "Senior Quality Engineer",
  "salary": 50646.66,
  "commission": 4303.53,
  "manager": "Tore Teresia",
  "department_name": "Operations",
  "city": "Panay",
  "country": "Philippines"
}, {
  "id": 63,
  "first_name": "Carlie",
  "surname": "Nower",
  "email": "cnower1q@pbs.org",
  "phone_number": "996-324-1682",
  "hire_date": "4/18/2019",
  "job_name": "Web Designer I",
  "salary": 108382.26,
  "commission": 1135.52,
  "manager": "Carlie Nower",
  "department_name": "IT",
  "city": "Chenzhuang",
  "country": "China"
}, {
  "id": 64,
  "first_name": "Katusha",
  "surname": "Putland",
  "email": "kputland1r@example.com",
  "phone_number": "339-802-5085",
  "hire_date": "5/26/2016",
  "job_name": "Clinical Specialist",
  "salary": 32158.6,
  "commission": 413.42,
  "manager": "Katusha Putland",
  "department_name": "Finance",
  "city": "Maru",
  "country": "Nigeria"
}, {
  "id": 65,
  "first_name": "Evie",
  "surname": "Cornfield",
  "email": "ecornfield1s@posterous.com",
  "phone_number": "418-219-7934",
  "hire_date": "6/1/2011",
  "job_name": "Staff Scientist",
  "salary": 73516.54,
  "commission": 1063.25,
  "manager": "Evie Cornfield",
  "department_name": "Sales",
  "city": "Xinhe",
  "country": "China"
}, {
  "id": 66,
  "first_name": "Gale",
  "surname": "Matignon",
  "email": "gmatignon1t@foxnews.com",
  "phone_number": "528-630-9614",
  "hire_date": "2/6/2003",
  "job_name": "Senior Editor",
  "salary": 51518.86,
  "commission": 3418.67,
  "manager": "Gale Matignon",
  "department_name": "IT",
  "city": "Itigi",
  "country": "Tanzania"
}, {
  "id": 67,
  "first_name": "Esteban",
  "surname": "Binham",
  "email": "ebinham1u@xinhuanet.com",
  "phone_number": "547-770-0240",
  "hire_date": "5/23/2017",
  "job_name": "Environmental Specialist",
  "salary": 52126.48,
  "commission": 4131.2,
  "manager": "Esteban Binham",
  "department_name": "Marketing",
  "city": "Neikeng",
  "country": "China"
}, {
  "id": 68,
  "first_name": "Marcellus",
  "surname": "Seywood",
  "email": "mseywood1v@canalblog.com",
  "phone_number": "453-249-5080",
  "hire_date": "7/10/2019",
  "job_name": "Research Associate",
  "salary": 45396.67,
  "commission": 2736.78,
  "manager": "Marcellus Seywood",
  "department_name": "Sales",
  "city": "Shilong",
  "country": "China"
}, {
  "id": 69,
  "first_name": "Gussy",
  "surname": "Southward",
  "email": "gsouthward1w@engadget.com",
  "phone_number": "987-323-5164",
  "hire_date": "7/26/2011",
  "job_name": "Financial Advisor",
  "salary": 105843.78,
  "commission": 827.51,
  "manager": "Gussy Southward",
  "department_name": "Sales",
  "city": "Smedjebacken",
  "country": "Sweden"
}, {
  "id": 70,
  "first_name": "Reeva",
  "surname": "McAneny",
  "email": "rmcaneny1x@sfgate.com",
  "phone_number": "254-365-5942",
  "hire_date": "9/1/2021",
  "job_name": "Community Outreach Specialist",
  "salary": 147143.87,
  "commission": 1378.56,
  "manager": "Reeva McAneny",
  "department_name": "Finance",
  "city": "Tobias Barreto",
  "country": "Brazil"
}, {
  "id": 71,
  "first_name": "Obie",
  "surname": "McMonnies",
  "email": "omcmonnies1y@dion.ne.jp",
  "phone_number": "693-812-9586",
  "hire_date": "4/6/2011",
  "job_name": "Dental Hygienist",
  "salary": 130353.67,
  "commission": 451.43,
  "manager": "Obie McMonnies",
  "department_name": "Operations",
  "city": "Xinglongquan",
  "country": "China"
}, {
  "id": 72,
  "first_name": "Boy",
  "surname": "Venour",
  "email": "bvenour1z@fda.gov",
  "phone_number": "417-122-2767",
  "hire_date": "10/13/2020",
  "job_name": "Marketing Assistant",
  "salary": 91773.51,
  "commission": 4462.69,
  "manager": "Boy Venour",
  "department_name": "Marketing",
  "city": "Springfield",
  "country": "United States"
}, {
  "id": 73,
  "first_name": "Olivie",
  "surname": "Janman",
  "email": "ojanman20@behance.net",
  "phone_number": "304-503-6870",
  "hire_date": "3/10/2013",
  "job_name": "Systems Administrator II",
  "salary": 43450.24,
  "commission": 3858.02,
  "manager": "Olivie Janman",
  "department_name": "Finance",
  "city": "Batan",
  "country": "Philippines"
}, {
  "id": 74,
  "first_name": "Norbert",
  "surname": "Colgan",
  "email": "ncolgan21@github.com",
  "phone_number": "217-961-7643",
  "hire_date": "1/20/2005",
  "job_name": "Database Administrator I",
  "salary": 116108.86,
  "commission": 4891.92,
  "manager": "Norbert Colgan",
  "department_name": "Sales",
  "city": "Ribeiro",
  "country": "Portugal"
}, {
  "id": 75,
  "first_name": "Melodee",
  "surname": "Mar",
  "email": "mmar22@1und1.de",
  "phone_number": "476-744-1322",
  "hire_date": "9/14/2017",
  "job_name": "Executive Secretary",
  "salary": 25800.23,
  "commission": 658.53,
  "manager": "Melodee Mar",
  "department_name": "IT",
  "city": "Minshan",
  "country": "China"
}, {
  "id": 76,
  "first_name": "Viv",
  "surname": "Gresham",
  "email": "vgresham23@blinklist.com",
  "phone_number": "754-262-0261",
  "hire_date": "7/31/2015",
  "job_name": "Media Manager III",
  "salary": 143654.46,
  "commission": 904.87,
  "manager": "Viv Gresham",
  "department_name": "Finance",
  "city": "Siemiątkowo",
  "country": "Poland"
}, {
  "id": 77,
  "first_name": "Cass",
  "surname": "Gallon",
  "email": "cgallon24@aol.com",
  "phone_number": "844-524-7620",
  "hire_date": "4/29/2022",
  "job_name": "Senior Developer",
  "salary": 48431.04,
  "commission": 2366.01,
  "manager": "Cass Gallon",
  "department_name": "Finance",
  "city": "Caiyuan",
  "country": "China"
}, {
  "id": 78,
  "first_name": "Innis",
  "surname": "Reddie",
  "email": "ireddie25@networksolutions.com",
  "phone_number": "552-908-9295",
  "hire_date": "7/9/2021",
  "job_name": "Nurse",
  "salary": 56774.46,
  "commission": 143.41,
  "manager": "Innis Reddie",
  "department_name": "IT",
  "city": "Sanqu",
  "country": "China"
}, {
  "id": 79,
  "first_name": "Georgine",
  "surname": "Giacopazzi",
  "email": "ggiacopazzi26@go.com",
  "phone_number": "622-445-8316",
  "hire_date": "1/18/2009",
  "job_name": "Civil Engineer",
  "salary": 141319.18,
  "commission": 3265.66,
  "manager": "Georgine Giacopazzi",
  "department_name": "IT",
  "city": "Zaozerne",
  "country": "Ukraine"
}, {
  "id": 80,
  "first_name": "Udale",
  "surname": "Ducroe",
  "email": "uducroe27@oracle.com",
  "phone_number": "238-836-4392",
  "hire_date": "9/17/2003",
  "job_name": "Quality Engineer",
  "salary": 95000.11,
  "commission": 794.17,
  "manager": "Udale Ducroe",
  "department_name": "Operations",
  "city": "Tupanciretã",
  "country": "Brazil"
}, {
  "id": 81,
  "first_name": "Katerine",
  "surname": "Robertz",
  "email": "krobertz28@noaa.gov",
  "phone_number": "910-588-2271",
  "hire_date": "3/25/2009",
  "job_name": "Senior Editor",
  "salary": 77497.23,
  "commission": 1463.72,
  "manager": "Katerine Robertz",
  "department_name": "Marketing",
  "city": "São Francisco",
  "country": "Brazil"
}, {
  "id": 82,
  "first_name": "Alissa",
  "surname": "Hayter",
  "email": "ahayter29@europa.eu",
  "phone_number": "342-274-5811",
  "hire_date": "5/31/2016",
  "job_name": "Senior Editor",
  "salary": 52861.77,
  "commission": 1558.38,
  "manager": "Alissa Hayter",
  "department_name": "Sales",
  "city": "Sinegor'ye",
  "country": "Russia"
}, {
  "id": 83,
  "first_name": "Shaun",
  "surname": "Orhtmann",
  "email": "sorhtmann2a@unesco.org",
  "phone_number": "120-101-9050",
  "hire_date": "6/19/2003",
  "job_name": "Tax Accountant",
  "salary": 131877.13,
  "commission": 1669.42,
  "manager": "Shaun Orhtmann",
  "department_name": "Marketing",
  "city": "Bourg-lès-Valence",
  "country": "France"
}, {
  "id": 84,
  "first_name": "Clifford",
  "surname": "Baswall",
  "email": "cbaswall2b@sakura.ne.jp",
  "phone_number": "428-718-4879",
  "hire_date": "6/25/2000",
  "job_name": "Desktop Support Technician",
  "salary": 67889.34,
  "commission": 3061.09,
  "manager": "Clifford Baswall",
  "department_name": "Sales",
  "city": "Qianwei",
  "country": "China"
}, {
  "id": 85,
  "first_name": "Alysia",
  "surname": "McCartney",
  "email": "amccartney2c@angelfire.com",
  "phone_number": "324-772-3060",
  "hire_date": "1/7/2015",
  "job_name": "Developer IV",
  "salary": 33561.38,
  "commission": 2620.43,
  "manager": "Alysia McCartney",
  "department_name": "Sales",
  "city": "Jajarkrajan",
  "country": "Indonesia"
}, {
  "id": 86,
  "first_name": "Rutherford",
  "surname": "Stranks",
  "email": "rstranks2d@miibeian.gov.cn",
  "phone_number": "286-624-3076",
  "hire_date": "12/29/2015",
  "job_name": "Human Resources Assistant I",
  "salary": 99297.1,
  "commission": 4107.4,
  "manager": "Rutherford Stranks",
  "department_name": "Sales",
  "city": "Jiekeng",
  "country": "China"
}, {
  "id": 87,
  "first_name": "Omar",
  "surname": "Haffenden",
  "email": "ohaffenden2e@yahoo.com",
  "phone_number": "708-762-5603",
  "hire_date": "11/17/2002",
  "job_name": "Software Engineer I",
  "salary": 126682.66,
  "commission": 2994.32,
  "manager": "Omar Haffenden",
  "department_name": "Marketing",
  "city": "Jiangjing",
  "country": "China"
}, {
  "id": 88,
  "first_name": "Gertie",
  "surname": "Kemmis",
  "email": "gkemmis2f@godaddy.com",
  "phone_number": "142-166-6587",
  "hire_date": "7/19/2001",
  "job_name": "Financial Analyst",
  "salary": 147981.3,
  "commission": 1473.55,
  "manager": "Gertie Kemmis",
  "department_name": "Marketing",
  "city": "Nanshe",
  "country": "China"
}, {
  "id": 89,
  "first_name": "Robert",
  "surname": "Hurlston",
  "email": "rhurlston2g@jigsy.com",
  "phone_number": "779-203-9979",
  "hire_date": "3/13/2021",
  "job_name": "Safety Technician III",
  "salary": 131408.67,
  "commission": 202.29,
  "manager": "Robert Hurlston",
  "department_name": "Marketing",
  "city": "Durrës",
  "country": "Albania"
}, {
  "id": 90,
  "first_name": "Evangelina",
  "surname": "Manby",
  "email": "emanby2h@php.net",
  "phone_number": "185-252-0033",
  "hire_date": "7/7/2019",
  "job_name": "Information Systems Manager",
  "salary": 104168.15,
  "commission": 1667.72,
  "manager": "Evangelina Manby",
  "department_name": "Finance",
  "city": "Yanjiang",
  "country": "China"
}, {
  "id": 91,
  "first_name": "Pearle",
  "surname": "Clapison",
  "email": "pclapison2i@home.pl",
  "phone_number": "775-970-8185",
  "hire_date": "10/21/2016",
  "job_name": "Structural Analysis Engineer",
  "salary": 144691.5,
  "commission": 4066.22,
  "manager": "Pearle Clapison",
  "department_name": "IT",
  "city": "As Sukhnah",
  "country": "Syria"
}, {
  "id": 92,
  "first_name": "Jamie",
  "surname": "Skaif",
  "email": "jskaif2j@mtv.com",
  "phone_number": "199-698-9865",
  "hire_date": "2/27/2015",
  "job_name": "Assistant Professor",
  "salary": 97058.05,
  "commission": 46.08,
  "manager": "Jamie Skaif",
  "department_name": "Sales",
  "city": "Mamedkala",
  "country": "Russia"
}, {
  "id": 93,
  "first_name": "Vicki",
  "surname": "Vittore",
  "email": "vvittore2k@tripod.com",
  "phone_number": "719-907-4582",
  "hire_date": "4/14/2018",
  "job_name": "Senior Developer",
  "salary": 40385.8,
  "commission": 4602.72,
  "manager": "Vicki Vittore",
  "department_name": "Sales",
  "city": "San Martín",
  "country": "Argentina"
}, {
  "id": 94,
  "first_name": "Ealasaid",
  "surname": "Merveille",
  "email": "emerveille2l@merriam-webster.com",
  "phone_number": "907-255-1622",
  "hire_date": "6/7/2012",
  "job_name": "Community Outreach Specialist",
  "salary": 104957.19,
  "commission": 3554.71,
  "manager": "Ealasaid Merveille",
  "department_name": "Sales",
  "city": "Bagakay",
  "country": "Philippines"
}, {
  "id": 95,
  "first_name": "Alyosha",
  "surname": "Bollom",
  "email": "abollom2m@hhs.gov",
  "phone_number": "236-603-7115",
  "hire_date": "7/9/2015",
  "job_name": "Executive Secretary",
  "salary": 132512.59,
  "commission": 1543.88,
  "manager": "Alyosha Bollom",
  "department_name": "Operations",
  "city": "Santana de Parnaíba",
  "country": "Brazil"
}, {
  "id": 96,
  "first_name": "Niven",
  "surname": "Dorling",
  "email": "ndorling2n@amazon.co.jp",
  "phone_number": "138-780-2986",
  "hire_date": "8/15/2003",
  "job_name": "Business Systems Development Analyst",
  "salary": 141277.62,
  "commission": 4472.58,
  "manager": "Niven Dorling",
  "department_name": "Marketing",
  "city": "Tanggungrejo",
  "country": "Indonesia"
}, {
  "id": 97,
  "first_name": "Cairistiona",
  "surname": "Tocknell",
  "email": "ctocknell2o@usda.gov",
  "phone_number": "473-442-8376",
  "hire_date": "11/13/2014",
  "job_name": "Project Manager",
  "salary": 71640.58,
  "commission": 4530.12,
  "manager": "Cairistiona Tocknell",
  "department_name": "IT",
  "city": "Huzhou",
  "country": "China"
}, {
  "id": 98,
  "first_name": "Dame",
  "surname": "Vairow",
  "email": "dvairow2p@e-recht24.de",
  "phone_number": "969-705-4245",
  "hire_date": "8/17/2008",
  "job_name": "Staff Scientist",
  "salary": 94454.72,
  "commission": 4657.88,
  "manager": "Dame Vairow",
  "department_name": "Sales",
  "city": "Carromeu",
  "country": "Portugal"
}, {
  "id": 99,
  "first_name": "Heindrick",
  "surname": "McGinlay",
  "email": "hmcginlay2q@surveymonkey.com",
  "phone_number": "437-726-7588",
  "hire_date": "11/11/2014",
  "job_name": "Technical Writer",
  "salary": 125002.18,
  "commission": 3668.72,
  "manager": "Heindrick McGinlay",
  "department_name": "Sales",
  "city": "Neietsu",
  "country": "South Korea"
}, {
  "id": 100,
  "first_name": "Lyndsay",
  "surname": "Beany",
  "email": "lbeany2r@prnewswire.com",
  "phone_number": "966-698-1822",
  "hire_date": "12/17/2011",
  "job_name": "Account Executive",
  "salary": 141820.06,
  "commission": 2212.35,
  "manager": "Lyndsay Beany",
  "department_name": "Operations",
  "city": "Novosin’kovo",
  "country": "Russia"
}]


  export const Dane = () => {
        return (
            zmienna
        )
    };