const zmienna = [{
    "first_name": "Arnuad",
    "surname": "Lorroway",
    "email": "hlorroway0@gravatar.com",
    "phone_number": "367-442-1735",
    "hire_date": "7/2/2019",
    "job_name": "Assistant Professor",
    "salary": 50,
    "commission": 67.23,
    "manager": "Herbie",
    "department_name": "Research and Development"
  }, {
    "first_name": "Cathrine",
    "surname": "Cayet",
    "email": "jcayet1@csmonitor.com",
    "phone_number": "217-875-5485",
    "hire_date": "1/27/2001",
    "job_name": "Design Engineer",
    "salary": 8,
    "commission": 91.93,
    "manager": "Julianna",
    "department_name": "Accounting"
  }, {
    "first_name": "Ike",
    "surname": "Sehorsch",
    "email": "jsehorsch2@g.co",
    "phone_number": "907-686-7892",
    "hire_date": "3/29/2006",
    "job_name": "Information Systems Manager",
    "salary": 66,
    "commission": 14.85,
    "manager": "Jyoti",
    "department_name": "Legal"
  }, {
    "first_name": "Esdras",
    "surname": "Duckerin",
    "email": "fduckerin3@oaic.gov.au",
    "phone_number": "879-143-4777",
    "hire_date": "9/3/2017",
    "job_name": "Assistant Professor",
    "salary": 34,
    "commission": 52.84,
    "manager": "Far",
    "department_name": "Research and Development"
  }, {
    "first_name": "Renard",
    "surname": "Crichmere",
    "email": "acrichmere4@webmd.com",
    "phone_number": "795-708-7771",
    "hire_date": "9/25/2005",
    "job_name": "Internal Auditor",
    "salary": 6,
    "commission": 42.45,
    "manager": "Annalee",
    "department_name": "Sales"
  }, {
    "first_name": "Jobie",
    "surname": "Filippov",
    "email": "kfilippov5@feedburner.com",
    "phone_number": "757-680-0139",
    "hire_date": "1/6/2009",
    "job_name": "Staff Scientist",
    "salary": 87,
    "commission": 15.51,
    "manager": "Kev",
    "department_name": "Sales"
  }, {
    "first_name": "Ursuline",
    "surname": "Burnip",
    "email": "mburnip6@usatoday.com",
    "phone_number": "613-752-2533",
    "hire_date": "4/13/2006",
    "job_name": "Occupational Therapist",
    "salary": 46,
    "commission": 98.58,
    "manager": "Madlen",
    "department_name": "Human Resources"
  }, {
    "first_name": "Adelheid",
    "surname": "McCome",
    "email": "bmccome7@redcross.org",
    "phone_number": "426-227-0550",
    "hire_date": "1/17/2017",
    "job_name": "Programmer Analyst I",
    "salary": 66,
    "commission": 89.11,
    "manager": "Bat",
    "department_name": "Support"
  }, {
    "first_name": "Gerri",
    "surname": "Bromehead",
    "email": "ebromehead8@columbia.edu",
    "phone_number": "509-706-8900",
    "hire_date": "5/14/2003",
    "job_name": "Accounting Assistant III",
    "salary": 54,
    "commission": 40.59,
    "manager": "Ethyl",
    "department_name": "Business Development"
  }, {
    "first_name": "Gayle",
    "surname": "Whale",
    "email": "dwhale9@discovery.com",
    "phone_number": "569-961-0809",
    "hire_date": "2/11/2005",
    "job_name": "Automation Specialist III",
    "salary": 23,
    "commission": 86.79,
    "manager": "Dwain",
    "department_name": "Research and Development"
  }, {
    "first_name": "Lesly",
    "surname": "Detheridge",
    "email": "adetheridgea@hao123.com",
    "phone_number": "279-391-0500",
    "hire_date": "5/6/2021",
    "job_name": "Associate Professor",
    "salary": 20,
    "commission": 84.63,
    "manager": "Arthur",
    "department_name": "Human Resources"
  }, {
    "first_name": "Lance",
    "surname": "Kropp",
    "email": "hkroppb@woothemes.com",
    "phone_number": "333-258-6241",
    "hire_date": "12/27/2013",
    "job_name": "Food Chemist",
    "salary": 86,
    "commission": 55.74,
    "manager": "Hollie",
    "department_name": "Legal"
  }, {
    "first_name": "Francoise",
    "surname": "Mordin",
    "email": "pmordinc@stumbleupon.com",
    "phone_number": "734-740-4080",
    "hire_date": "4/11/2003",
    "job_name": "Nurse",
    "salary": 38,
    "commission": 57.78,
    "manager": "Papagena",
    "department_name": "Accounting"
  }, {
    "first_name": "Trefor",
    "surname": "Fullicks",
    "email": "pfullicksd@blogs.com",
    "phone_number": "241-385-6019",
    "hire_date": "8/10/2006",
    "job_name": "Analyst Programmer",
    "salary": 17,
    "commission": 81.15,
    "manager": "Paule",
    "department_name": "Training"
  }, {
    "first_name": "Erinna",
    "surname": "Hendrikse",
    "email": "lhendriksee@constantcontact.com",
    "phone_number": "119-156-9823",
    "hire_date": "1/1/2005",
    "job_name": "Recruiter",
    "salary": 39,
    "commission": 31.78,
    "manager": "Lida",
    "department_name": "Services"
  }, {
    "first_name": "Gunter",
    "surname": "Bartell",
    "email": "sbartellf@prnewswire.com",
    "phone_number": "364-212-6274",
    "hire_date": "12/31/2009",
    "job_name": "Editor",
    "salary": 12,
    "commission": 3.69,
    "manager": "Sherwynd",
    "department_name": "Accounting"
  }, {
    "first_name": "Mose",
    "surname": "Iorio",
    "email": "rioriog@rambler.ru",
    "phone_number": "521-635-5948",
    "hire_date": "8/19/2007",
    "job_name": "Programmer Analyst IV",
    "salary": 57,
    "commission": 20.26,
    "manager": "Reid",
    "department_name": "Business Development"
  }, {
    "first_name": "Salvatore",
    "surname": "Dallinder",
    "email": "mdallinderh@xing.com",
    "phone_number": "801-243-6912",
    "hire_date": "7/4/2009",
    "job_name": "Environmental Tech",
    "salary": 26,
    "commission": 96.28,
    "manager": "Mario",
    "department_name": "Accounting"
  }, {
    "first_name": "Christopher",
    "surname": "Petroulis",
    "email": "tpetroulisi@boston.com",
    "phone_number": "917-279-8776",
    "hire_date": "7/5/2005",
    "job_name": "Office Assistant I",
    "salary": 87,
    "commission": 90.11,
    "manager": "Tiebout",
    "department_name": "Product Management"
  }, {
    "first_name": "Evangelia",
    "surname": "Mortimer",
    "email": "bmortimerj@tinyurl.com",
    "phone_number": "272-794-4385",
    "hire_date": "7/2/2013",
    "job_name": "Internal Auditor",
    "salary": 39,
    "commission": 82.71,
    "manager": "Brittne",
    "department_name": "Engineering"
  }, {
    "first_name": "Marc",
    "surname": "Caze",
    "email": "kcazek@toplist.cz",
    "phone_number": "805-943-4329",
    "hire_date": "8/3/2014",
    "job_name": "Graphic Designer",
    "salary": 90,
    "commission": 49.4,
    "manager": "Kerrie",
    "department_name": "Sales"
  }, {
    "first_name": "Frederic",
    "surname": "Christie",
    "email": "cchristiel@fema.gov",
    "phone_number": "678-221-2795",
    "hire_date": "1/28/2014",
    "job_name": "Administrative Officer",
    "salary": 97,
    "commission": 90.05,
    "manager": "Cecily",
    "department_name": "Support"
  }, {
    "first_name": "Clarke",
    "surname": "Massie",
    "email": "bmassiem@feedburner.com",
    "phone_number": "738-823-5227",
    "hire_date": "6/18/2021",
    "job_name": "Database Administrator IV",
    "salary": 65,
    "commission": 20.38,
    "manager": "Broddy",
    "department_name": "Marketing"
  }, {
    "first_name": "Coleman",
    "surname": "Godthaab",
    "email": "agodthaabn@amazonaws.com",
    "phone_number": "882-444-4170",
    "hire_date": "5/22/2001",
    "job_name": "Recruiting Manager",
    "salary": 11,
    "commission": 67.96,
    "manager": "Aline",
    "department_name": "Engineering"
  }, {
    "first_name": "Janessa",
    "surname": "Lucio",
    "email": "flucioo@china.com.cn",
    "phone_number": "302-160-5865",
    "hire_date": "5/26/2022",
    "job_name": "Research Nurse",
    "salary": 25,
    "commission": 41.87,
    "manager": "Fraser",
    "department_name": "Support"
  }, {
    "first_name": "Mattie",
    "surname": "Kingcott",
    "email": "mkingcottp@uol.com.br",
    "phone_number": "330-688-2237",
    "hire_date": "5/5/2020",
    "job_name": "Social Worker",
    "salary": 10,
    "commission": 56.11,
    "manager": "Malvin",
    "department_name": "Engineering"
  }, {
    "first_name": "Melanie",
    "surname": "Fraschetti",
    "email": "gfraschettiq@stumbleupon.com",
    "phone_number": "671-685-3139",
    "hire_date": "5/23/2011",
    "job_name": "Assistant Media Planner",
    "salary": 99,
    "commission": 26.24,
    "manager": "Gayleen",
    "department_name": "Sales"
  }, {
    "first_name": "Mickie",
    "surname": "Middas",
    "email": "bmiddasr@imageshack.us",
    "phone_number": "516-529-8641",
    "hire_date": "9/3/2019",
    "job_name": "Food Chemist",
    "salary": 81,
    "commission": 6.09,
    "manager": "Bobbie",
    "department_name": "Marketing"
  }, {
    "first_name": "Clair",
    "surname": "Hickeringill",
    "email": "ahickeringills@columbia.edu",
    "phone_number": "492-152-7011",
    "hire_date": "6/23/2022",
    "job_name": "Senior Cost Accountant",
    "salary": 55,
    "commission": 7.2,
    "manager": "Avivah",
    "department_name": "Support"
  }, {
    "first_name": "Shaw",
    "surname": "Davidofski",
    "email": "mdavidofskit@walmart.com",
    "phone_number": "358-711-3397",
    "hire_date": "4/19/2020",
    "job_name": "Business Systems Development Analyst",
    "salary": 53,
    "commission": 53.21,
    "manager": "Mora",
    "department_name": "Support"
  }, {
    "first_name": "Barton",
    "surname": "Diamant",
    "email": "wdiamantu@devhub.com",
    "phone_number": "859-725-2100",
    "hire_date": "3/3/2013",
    "job_name": "General Manager",
    "salary": 28,
    "commission": 12.52,
    "manager": "Wilie",
    "department_name": "Research and Development"
  }, {
    "first_name": "Ferdinanda",
    "surname": "Alesbrook",
    "email": "yalesbrookv@com.com",
    "phone_number": "708-407-3799",
    "hire_date": "1/13/2006",
    "job_name": "Media Manager II",
    "salary": 69,
    "commission": 99.53,
    "manager": "Yalonda",
    "department_name": "Engineering"
  }, {
    "first_name": "Jammal",
    "surname": "McKune",
    "email": "rmckunew@hc360.com",
    "phone_number": "349-205-0861",
    "hire_date": "11/28/2014",
    "job_name": "Senior Developer",
    "salary": 24,
    "commission": 2.66,
    "manager": "Randy",
    "department_name": "Accounting"
  }, {
    "first_name": "Wayland",
    "surname": "Lount",
    "email": "mlountx@hibu.com",
    "phone_number": "305-731-5008",
    "hire_date": "7/15/2021",
    "job_name": "Electrical Engineer",
    "salary": 68,
    "commission": 45.28,
    "manager": "Maggi",
    "department_name": "Business Development"
  }, {
    "first_name": "Jule",
    "surname": "Sawday",
    "email": "lsawdayy@biglobe.ne.jp",
    "phone_number": "483-652-7897",
    "hire_date": "2/13/2019",
    "job_name": "Assistant Professor",
    "salary": 93,
    "commission": 73.23,
    "manager": "Lazarus",
    "department_name": "Research and Development"
  }, {
    "first_name": "Mirabella",
    "surname": "Kleis",
    "email": "mkleisz@geocities.com",
    "phone_number": "103-748-4068",
    "hire_date": "3/7/2020",
    "job_name": "Geologist IV",
    "salary": 16,
    "commission": 50.09,
    "manager": "Merill",
    "department_name": "Training"
  }, {
    "first_name": "Shawna",
    "surname": "Showte",
    "email": "rshowte10@google.pl",
    "phone_number": "100-907-6696",
    "hire_date": "8/25/2021",
    "job_name": "Chief Design Engineer",
    "salary": 30,
    "commission": 16.7,
    "manager": "Ronni",
    "department_name": "Engineering"
  }, {
    "first_name": "Cordy",
    "surname": "Moffatt",
    "email": "tmoffatt11@amazon.de",
    "phone_number": "652-298-9081",
    "hire_date": "12/27/2007",
    "job_name": "Nurse Practicioner",
    "salary": 30,
    "commission": 73.77,
    "manager": "Tamarra",
    "department_name": "Engineering"
  }, {
    "first_name": "Timofei",
    "surname": "Boatman",
    "email": "dboatman12@zimbio.com",
    "phone_number": "434-608-0675",
    "hire_date": "9/17/2019",
    "job_name": "Environmental Specialist",
    "salary": 26,
    "commission": 99.38,
    "manager": "Domenico",
    "department_name": "Accounting"
  }, {
    "first_name": "Ophelia",
    "surname": "Gunnell",
    "email": "egunnell13@sourceforge.net",
    "phone_number": "896-446-6630",
    "hire_date": "11/3/2013",
    "job_name": "Software Test Engineer IV",
    "salary": 27,
    "commission": 87.18,
    "manager": "Eugenia",
    "department_name": "Human Resources"
  }, {
    "first_name": "Lila",
    "surname": "Whatley",
    "email": "kwhatley14@springer.com",
    "phone_number": "438-637-9899",
    "hire_date": "5/9/2000",
    "job_name": "Financial Advisor",
    "salary": 98,
    "commission": 4.96,
    "manager": "Kalina",
    "department_name": "Training"
  }, {
    "first_name": "Lela",
    "surname": "Look",
    "email": "plook15@diigo.com",
    "phone_number": "908-442-9649",
    "hire_date": "11/2/2012",
    "job_name": "Research Assistant I",
    "salary": 46,
    "commission": 26.76,
    "manager": "Paulie",
    "department_name": "Support"
  }, {
    "first_name": "Liz",
    "surname": "Dybell",
    "email": "odybell16@simplemachines.org",
    "phone_number": "663-646-5248",
    "hire_date": "10/31/2019",
    "job_name": "Sales Representative",
    "salary": 85,
    "commission": 54.95,
    "manager": "Osmond",
    "department_name": "Legal"
  }, {
    "first_name": "Millisent",
    "surname": "Sutherby",
    "email": "ssutherby17@blog.com",
    "phone_number": "470-686-7514",
    "hire_date": "8/26/2000",
    "job_name": "Director of Sales",
    "salary": 15,
    "commission": 74.21,
    "manager": "Shadow",
    "department_name": "Sales"
  }, {
    "first_name": "Nanete",
    "surname": "Higounet",
    "email": "nhigounet18@vistaprint.com",
    "phone_number": "175-526-2038",
    "hire_date": "12/23/2002",
    "job_name": "Nurse Practicioner",
    "salary": 6,
    "commission": 23.06,
    "manager": "Nell",
    "department_name": "Accounting"
  }, {
    "first_name": "Felix",
    "surname": "Probets",
    "email": "dprobets19@istockphoto.com",
    "phone_number": "401-638-6952",
    "hire_date": "2/5/2008",
    "job_name": "Executive Secretary",
    "salary": 37,
    "commission": 2.24,
    "manager": "Davon",
    "department_name": "Human Resources"
  }, {
    "first_name": "Idelle",
    "surname": "Oakley",
    "email": "coakley1a@google.nl",
    "phone_number": "108-436-5512",
    "hire_date": "6/28/2000",
    "job_name": "Biostatistician III",
    "salary": 69,
    "commission": 66.09,
    "manager": "Claiborn",
    "department_name": "Marketing"
  }, {
    "first_name": "Ferd",
    "surname": "Hassard",
    "email": "chassard1b@engadget.com",
    "phone_number": "684-504-6052",
    "hire_date": "3/8/2016",
    "job_name": "Sales Representative",
    "salary": 24,
    "commission": 3.82,
    "manager": "Carley",
    "department_name": "Human Resources"
  }, {
    "first_name": "Alfreda",
    "surname": "Menauteau",
    "email": "jmenauteau1c@g.co",
    "phone_number": "198-467-7611",
    "hire_date": "8/30/2013",
    "job_name": "Electrical Engineer",
    "salary": 80,
    "commission": 95.18,
    "manager": "Julie",
    "department_name": "Marketing"
  }, {
    "first_name": "Coleman",
    "surname": "Barbara",
    "email": "mbarbara1d@google.pl",
    "phone_number": "193-134-6544",
    "hire_date": "10/22/2005",
    "job_name": "Developer II",
    "salary": 3,
    "commission": 73.5,
    "manager": "Marlin",
    "department_name": "Engineering"
  }, {
    "first_name": "Tris",
    "surname": "Shama",
    "email": "mshama1e@psu.edu",
    "phone_number": "246-620-3928",
    "hire_date": "10/12/2008",
    "job_name": "VP Sales",
    "salary": 45,
    "commission": 36.79,
    "manager": "Marsiella",
    "department_name": "Training"
  }, {
    "first_name": "Evangelia",
    "surname": "Kilpin",
    "email": "rkilpin1f@moonfruit.com",
    "phone_number": "765-666-5753",
    "hire_date": "12/15/2016",
    "job_name": "GIS Technical Architect",
    "salary": 99,
    "commission": 52.53,
    "manager": "Rocky",
    "department_name": "Support"
  }, {
    "first_name": "Baudoin",
    "surname": "Hacker",
    "email": "hhacker1g@imgur.com",
    "phone_number": "391-271-9795",
    "hire_date": "10/16/2008",
    "job_name": "Sales Representative",
    "salary": 37,
    "commission": 7.01,
    "manager": "Helsa",
    "department_name": "Sales"
  }, {
    "first_name": "Alphard",
    "surname": "Pie",
    "email": "hpie1h@behance.net",
    "phone_number": "232-261-9998",
    "hire_date": "10/31/2015",
    "job_name": "Food Chemist",
    "salary": 31,
    "commission": 22.77,
    "manager": "Hillary",
    "department_name": "Accounting"
  }, {
    "first_name": "Carita",
    "surname": "Necrews",
    "email": "mnecrews1i@un.org",
    "phone_number": "259-549-9235",
    "hire_date": "4/12/2010",
    "job_name": "Senior Developer",
    "salary": 24,
    "commission": 34.95,
    "manager": "Mathilde",
    "department_name": "Training"
  }, {
    "first_name": "Norbert",
    "surname": "Busby",
    "email": "mbusby1j@wp.com",
    "phone_number": "387-875-9727",
    "hire_date": "9/30/2022",
    "job_name": "Chief Design Engineer",
    "salary": 66,
    "commission": 55.96,
    "manager": "Myrna",
    "department_name": "Legal"
  }, {
    "first_name": "Emelda",
    "surname": "Shimmings",
    "email": "tshimmings1k@dropbox.com",
    "phone_number": "244-326-4855",
    "hire_date": "9/29/2003",
    "job_name": "Programmer IV",
    "salary": 25,
    "commission": 94.62,
    "manager": "Tiffi",
    "department_name": "Marketing"
  }, {
    "first_name": "Alvin",
    "surname": "Bunyan",
    "email": "bbunyan1l@unc.edu",
    "phone_number": "973-937-5757",
    "hire_date": "2/6/2008",
    "job_name": "Nurse Practicioner",
    "salary": 66,
    "commission": 81.36,
    "manager": "Barthel",
    "department_name": "Services"
  }, {
    "first_name": "Lucie",
    "surname": "Renison",
    "email": "srenison1m@g.co",
    "phone_number": "152-503-5386",
    "hire_date": "9/8/2020",
    "job_name": "Web Designer II",
    "salary": 29,
    "commission": 70.89,
    "manager": "Sherline",
    "department_name": "Support"
  }, {
    "first_name": "Edlin",
    "surname": "Shmyr",
    "email": "hshmyr1n@hexun.com",
    "phone_number": "314-838-2782",
    "hire_date": "11/16/2006",
    "job_name": "Automation Specialist III",
    "salary": 4,
    "commission": 17.63,
    "manager": "Humfrey",
    "department_name": "Training"
  }, {
    "first_name": "Elvera",
    "surname": "Jiroutek",
    "email": "tjiroutek1o@fda.gov",
    "phone_number": "483-757-3093",
    "hire_date": "3/16/2004",
    "job_name": "Accountant I",
    "salary": 99,
    "commission": 46.7,
    "manager": "Tobiah",
    "department_name": "Legal"
  }, {
    "first_name": "Valentin",
    "surname": "Dami",
    "email": "rdami1p@admin.ch",
    "phone_number": "492-257-6338",
    "hire_date": "10/23/2022",
    "job_name": "Chief Design Engineer",
    "salary": 16,
    "commission": 99.99,
    "manager": "Rafaellle",
    "department_name": "Sales"
  }, {
    "first_name": "Myrwyn",
    "surname": "Charker",
    "email": "mcharker1q@usnews.com",
    "phone_number": "799-560-1858",
    "hire_date": "10/31/2001",
    "job_name": "Quality Control Specialist",
    "salary": 60,
    "commission": 39.96,
    "manager": "Marty",
    "department_name": "Business Development"
  }, {
    "first_name": "Devonna",
    "surname": "Arr",
    "email": "aarr1r@1und1.de",
    "phone_number": "295-279-1957",
    "hire_date": "5/19/2007",
    "job_name": "Budget/Accounting Analyst II",
    "salary": 59,
    "commission": 87.68,
    "manager": "Alexio",
    "department_name": "Training"
  }, {
    "first_name": "Mateo",
    "surname": "Schiesterl",
    "email": "sschiesterl1s@buzzfeed.com",
    "phone_number": "506-799-3374",
    "hire_date": "8/5/2011",
    "job_name": "Data Coordinator",
    "salary": 64,
    "commission": 40.8,
    "manager": "Steve",
    "department_name": "Research and Development"
  }, {
    "first_name": "Stacia",
    "surname": "Hunsworth",
    "email": "whunsworth1t@pinterest.com",
    "phone_number": "370-971-1016",
    "hire_date": "6/28/2002",
    "job_name": "Information Systems Manager",
    "salary": 9,
    "commission": 13.88,
    "manager": "Weston",
    "department_name": "Accounting"
  }, {
    "first_name": "Patrick",
    "surname": "Bodega",
    "email": "sbodega1u@loc.gov",
    "phone_number": "466-518-2962",
    "hire_date": "12/21/2006",
    "job_name": "Electrical Engineer",
    "salary": 18,
    "commission": 90.7,
    "manager": "Salmon",
    "department_name": "Human Resources"
  }, {
    "first_name": "Shirley",
    "surname": "Spellissy",
    "email": "nspellissy1v@yale.edu",
    "phone_number": "600-978-9096",
    "hire_date": "10/23/2019",
    "job_name": "Staff Accountant II",
    "salary": 88,
    "commission": 66.16,
    "manager": "Nevile",
    "department_name": "Human Resources"
  }, {
    "first_name": "Johan",
    "surname": "Barg",
    "email": "bbarg1w@free.fr",
    "phone_number": "563-331-6562",
    "hire_date": "7/16/2012",
    "job_name": "Community Outreach Specialist",
    "salary": 42,
    "commission": 67.14,
    "manager": "Borg",
    "department_name": "Business Development"
  }, {
    "first_name": "Alecia",
    "surname": "Garrud",
    "email": "kgarrud1x@google.pl",
    "phone_number": "296-190-5670",
    "hire_date": "10/1/2015",
    "job_name": "Design Engineer",
    "salary": 10,
    "commission": 79.69,
    "manager": "Karilynn",
    "department_name": "Research and Development"
  }, {
    "first_name": "Florentia",
    "surname": "Leatham",
    "email": "mleatham1y@goo.ne.jp",
    "phone_number": "791-588-7138",
    "hire_date": "11/12/2012",
    "job_name": "Product Engineer",
    "salary": 79,
    "commission": 83.37,
    "manager": "Marjy",
    "department_name": "Marketing"
  }, {
    "first_name": "Nadya",
    "surname": "Meanwell",
    "email": "ameanwell1z@technorati.com",
    "phone_number": "762-738-4846",
    "hire_date": "12/7/2011",
    "job_name": "Administrative Officer",
    "salary": 30,
    "commission": 86.79,
    "manager": "Ariana",
    "department_name": "Legal"
  }, {
    "first_name": "Tanhya",
    "surname": "Philliskirk",
    "email": "wphilliskirk20@usatoday.com",
    "phone_number": "641-635-3001",
    "hire_date": "3/30/2019",
    "job_name": "Geologist I",
    "salary": 10,
    "commission": 40.64,
    "manager": "Woodman",
    "department_name": "Support"
  }, {
    "first_name": "Shawnee",
    "surname": "Mollnar",
    "email": "tmollnar21@hc360.com",
    "phone_number": "940-997-7348",
    "hire_date": "5/11/2006",
    "job_name": "Editor",
    "salary": 90,
    "commission": 29.83,
    "manager": "Thia",
    "department_name": "Support"
  }, {
    "first_name": "Clair",
    "surname": "Avrahamian",
    "email": "ravrahamian22@samsung.com",
    "phone_number": "233-418-7403",
    "hire_date": "4/25/2016",
    "job_name": "Teacher",
    "salary": 68,
    "commission": 96.35,
    "manager": "Rockey",
    "department_name": "Support"
  }, {
    "first_name": "Tricia",
    "surname": "Hounsom",
    "email": "dhounsom23@hao123.com",
    "phone_number": "445-562-9169",
    "hire_date": "10/27/2017",
    "job_name": "Research Associate",
    "salary": 9,
    "commission": 51.96,
    "manager": "Dov",
    "department_name": "Marketing"
  }, {
    "first_name": "Stanfield",
    "surname": "Mitchener",
    "email": "cmitchener24@fema.gov",
    "phone_number": "609-690-5173",
    "hire_date": "6/17/2014",
    "job_name": "Structural Engineer",
    "salary": 70,
    "commission": 28.87,
    "manager": "Cedric",
    "department_name": "Product Management"
  }, {
    "first_name": "Aileen",
    "surname": "Upstell",
    "email": "jupstell25@smh.com.au",
    "phone_number": "556-302-5595",
    "hire_date": "3/26/2014",
    "job_name": "Research Associate",
    "salary": 92,
    "commission": 58.12,
    "manager": "Julio",
    "department_name": "Sales"
  }, {
    "first_name": "Doralynn",
    "surname": "Calderon",
    "email": "rcalderon26@google.nl",
    "phone_number": "258-499-5446",
    "hire_date": "1/17/2011",
    "job_name": "Biostatistician III",
    "salary": 77,
    "commission": 84.41,
    "manager": "Rutger",
    "department_name": "Business Development"
  }, {
    "first_name": "Edeline",
    "surname": "Nelle",
    "email": "dnelle27@nytimes.com",
    "phone_number": "404-169-2308",
    "hire_date": "7/3/2013",
    "job_name": "Health Coach I",
    "salary": 48,
    "commission": 38.67,
    "manager": "Demeter",
    "department_name": "Legal"
  }, {
    "first_name": "Kailey",
    "surname": "O'Sullivan",
    "email": "aosullivan28@addtoany.com",
    "phone_number": "273-122-4623",
    "hire_date": "8/4/2000",
    "job_name": "Editor",
    "salary": 80,
    "commission": 14.9,
    "manager": "Amalie",
    "department_name": "Product Management"
  }, {
    "first_name": "Brander",
    "surname": "Baylis",
    "email": "cbaylis29@bravesites.com",
    "phone_number": "910-941-8925",
    "hire_date": "10/17/2015",
    "job_name": "Community Outreach Specialist",
    "salary": 20,
    "commission": 5.68,
    "manager": "Chrisy",
    "department_name": "Engineering"
  }, {
    "first_name": "Sabrina",
    "surname": "O'Kenny",
    "email": "vokenny2a@1688.com",
    "phone_number": "249-555-3212",
    "hire_date": "10/3/2009",
    "job_name": "Sales Representative",
    "salary": 45,
    "commission": 40.51,
    "manager": "Victoria",
    "department_name": "Engineering"
  }, {
    "first_name": "Lynne",
    "surname": "Fairbrass",
    "email": "efairbrass2b@gnu.org",
    "phone_number": "443-836-5560",
    "hire_date": "3/12/2003",
    "job_name": "Engineer III",
    "salary": 98,
    "commission": 20.26,
    "manager": "Ericka",
    "department_name": "Services"
  }, {
    "first_name": "Washington",
    "surname": "Crosi",
    "email": "mcrosi2c@google.com.hk",
    "phone_number": "877-130-3580",
    "hire_date": "8/22/2013",
    "job_name": "Account Executive",
    "salary": 10,
    "commission": 67.86,
    "manager": "Merilyn",
    "department_name": "Research and Development"
  }, {
    "first_name": "Liana",
    "surname": "Petrello",
    "email": "mpetrello2d@uiuc.edu",
    "phone_number": "304-584-5311",
    "hire_date": "3/31/2019",
    "job_name": "Office Assistant IV",
    "salary": 99,
    "commission": 12.55,
    "manager": "Murvyn",
    "department_name": "Sales"
  }, {
    "first_name": "Roshelle",
    "surname": "Buckingham",
    "email": "sbuckingham2e@theglobeandmail.com",
    "phone_number": "128-199-5568",
    "hire_date": "5/1/2000",
    "job_name": "Social Worker",
    "salary": 23,
    "commission": 5.92,
    "manager": "Sylvia",
    "department_name": "Support"
  }, {
    "first_name": "Yolanthe",
    "surname": "Breckin",
    "email": "lbreckin2f@friendfeed.com",
    "phone_number": "853-783-4414",
    "hire_date": "1/24/2007",
    "job_name": "Mechanical Systems Engineer",
    "salary": 68,
    "commission": 21.57,
    "manager": "Leon",
    "department_name": "Product Management"
  }, {
    "first_name": "Salem",
    "surname": "Triplet",
    "email": "striplet2g@exblog.jp",
    "phone_number": "438-848-9423",
    "hire_date": "9/27/2004",
    "job_name": "Sales Representative",
    "salary": 84,
    "commission": 10.42,
    "manager": "Shela",
    "department_name": "Marketing"
  }, {
    "first_name": "Joane",
    "surname": "Bartholomieu",
    "email": "ibartholomieu2h@vkontakte.ru",
    "phone_number": "431-700-6527",
    "hire_date": "12/10/2017",
    "job_name": "Mechanical Systems Engineer",
    "salary": 39,
    "commission": 72.01,
    "manager": "Ibbie",
    "department_name": "Product Management"
  }, {
    "first_name": "Ajay",
    "surname": "Grattan",
    "email": "dgrattan2i@reuters.com",
    "phone_number": "334-750-7303",
    "hire_date": "4/9/2005",
    "job_name": "Assistant Professor",
    "salary": 85,
    "commission": 76.43,
    "manager": "Dick",
    "department_name": "Training"
  }, {
    "first_name": "Marlyn",
    "surname": "Muckleston",
    "email": "tmuckleston2j@auda.org.au",
    "phone_number": "961-260-5057",
    "hire_date": "2/19/2009",
    "job_name": "Administrative Assistant IV",
    "salary": 49,
    "commission": 8.93,
    "manager": "Tess",
    "department_name": "Training"
  }, {
    "first_name": "Darsey",
    "surname": "Milmith",
    "email": "tmilmith2k@google.de",
    "phone_number": "184-291-5730",
    "hire_date": "5/20/2000",
    "job_name": "Teacher",
    "salary": 99,
    "commission": 15.41,
    "manager": "Tess",
    "department_name": "Engineering"
  }, {
    "first_name": "Hali",
    "surname": "Ellor",
    "email": "dellor2l@adobe.com",
    "phone_number": "968-518-3802",
    "hire_date": "12/2/2003",
    "job_name": "Help Desk Technician",
    "salary": 67,
    "commission": 87.54,
    "manager": "Darill",
    "department_name": "Accounting"
  }, {
    "first_name": "Killie",
    "surname": "Darthe",
    "email": "mdarthe2m@noaa.gov",
    "phone_number": "491-734-8186",
    "hire_date": "12/5/2002",
    "job_name": "Assistant Professor",
    "salary": 11,
    "commission": 83.35,
    "manager": "Marys",
    "department_name": "Sales"
  }, {
    "first_name": "Jeno",
    "surname": "Laidel",
    "email": "blaidel2n@opera.com",
    "phone_number": "212-491-4395",
    "hire_date": "12/7/2012",
    "job_name": "Occupational Therapist",
    "salary": 44,
    "commission": 79.41,
    "manager": "Barny",
    "department_name": "Sales"
  }, {
    "first_name": "Onida",
    "surname": "Karlolczak",
    "email": "dkarlolczak2o@hhs.gov",
    "phone_number": "441-499-3619",
    "hire_date": "12/16/2018",
    "job_name": "Structural Engineer",
    "salary": 84,
    "commission": 37.65,
    "manager": "Dougy",
    "department_name": "Services"
  }, {
    "first_name": "Diarmid",
    "surname": "Kleeman",
    "email": "rkleeman2p@51.la",
    "phone_number": "751-271-9609",
    "hire_date": "4/8/2006",
    "job_name": "Systems Administrator IV",
    "salary": 42,
    "commission": 43.24,
    "manager": "Roselin",
    "department_name": "Business Development"
  }, {
    "first_name": "Sheela",
    "surname": "Locker",
    "email": "clocker2q@soup.io",
    "phone_number": "387-474-3791",
    "hire_date": "11/3/2009",
    "job_name": "Account Executive",
    "salary": 24,
    "commission": 28.11,
    "manager": "Constancy",
    "department_name": "Training"
  }, {
    "first_name": "Jarrett",
    "surname": "Kinlock",
    "email": "jkinlock2r@yahoo.com",
    "phone_number": "701-381-8461",
    "hire_date": "1/14/2005",
    "job_name": "Account Coordinator",
    "salary": 51,
    "commission": 19.63,
    "manager": "Joelly",
    "department_name": "Services"
  }]


  export const Dane = () => {
        return (
            zmienna
        )
    };